apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-worker
  template:
    metadata:
      labels:
        app: receipt-worker
    spec:
      containers:
        - name: worker
          image: liliaph7/worker:latest
          env:
            - name: QUEUE_URL
              value: "https://sqs.us-east-1.amazonaws.com/984034935132/ventas-queue"

            - name: AWS_REGION
              value: "us-east-1"

            - name: BUCKET_NAME
              value: "673256-esi3898k-examen2"

            - name: SNS_TOPIC_ARN
              value: "arn:aws:sns:us-east-1:984034935132:ventas-topic"

            - name: PDF_URL
              value: "http://pdf-generator:3000"

            - name: NOTIFIER_URL
              value: "http://notifier:3000"

            - name: DB_HOST
              value: "terraform-20260502002828213500000002.cw791jmibie0.us-east-1.rds.amazonaws.com"

            - name: DB_USER
              value: "postgres"

            - name: DB_PASSWORD
              value: "password12366677"

            - name: DB_NAME
              value: "postgres"